# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Rakeshsuku.github.io/my_nbdev_tutorial/"

git_url = "https://github.com/Rakeshsuku/my_nbdev_tutorial/tree/master/"

def custom_doc_links(name): return None
